name: CXFundamental
main: cxplugins.cxfundamental.minecraft.plugin.CXFundamentalMain
version: 1.6.2
depend: [CXBaseRuntime]
commands:
  cxp:
    description: CXFundamental
    usage: /cxp
    permission: cxfundamental.op
    permission-message: You don't have <permission>
  permissions:
    cxfundamental.op:
      description: CXFundamental permissions for op
      default: Op


